services:
  - type: web
    name: accessibility-analyzer-api
    env: docker
    dockerContext: ./server
    dockerfilePath: ./server/Dockerfile
    plan: free
    region: oregon
    branch: master
    healthCheckPath: /health
    envVars:
      - key: PORT
        value: 8000
      - key: PYTHONUNBUFFERED
        value: "1"
      - key: PLAYWRIGHT_BROWSERS_PATH
        value: /ms-playwright
